#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to 301
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
old_string="try_files \$uri \$uri\/ =404;\n	}"
new_string="${old_string}\n\n	    location \/redirect_me {\n		try_files \$uri =301;\n	}"
sed -i "N; s/$old_string/$new_string/g" /etc/nginx/sites-available/default 
service nginx restart
